# Generated by Django 5.0.3 on 2024-03-30 11:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("FarmerBora_App", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="profile_picture",
            field=models.FileField(blank=True, null=True, upload_to="pics"),
        ),
    ]
