# Generated by Django 5.0.3 on 2024-04-02 01:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("FarmerBora_App", "0003_category_author_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="description",
            field=models.TextField(default="description"),
        ),
    ]
