# Generated by Django 5.0.3 on 2024-04-07 00:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("FarmerBora_App", "0010_alter_post_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="approved",
            field=models.BooleanField(default=True),
        ),
    ]
